export const SET_USER = "SET_USER";
export const ERRORS = "ERRORS";
export const SET_PROFILE = "SET_PROFILE";
export const SET_PROFILES = "SET_PROFILES";
export const DELETE_PROFILE = "DELETE_PROFILE";
export const FETCH_MEDICINE_PRODUCTS_REQUEST = 'FETCH_MEDICINE_PRODUCTS_REQUEST';
export const FETCH_MEDICINE_PRODUCTS_SUCCESS = 'FETCH_MEDICINE_PRODUCTS_SUCCESS';
export const FETCH_MEDICINE_PRODUCTS_FAILURE = 'FETCH_MEDICINE_PRODUCTS_FAILURE';
